title: Chen Qiao's Blog
description: > # this means to ignore newlines until "baseurl:"
  Hope you would know me better with the stuff here.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qiaochen.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chen Qiao (乔辰/喬辰) # add your name
author-img: chenqiao.jpg # add your photo
about-author: Researcher/Engineer interested in Machine Learning and NLP. In addition to writing codes for making sense of data, I write texts to appreciate life and nature. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: qiaochen # add your Github handle
social-linkedin: chen-qiao-hku # add your Linkedin handle
social-email: cqiaohku@gmail.com # add your Email address

# Disqus
discus-identifier: qiaochen-blog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
